// Generated by CoffeeScript 1.3.1
var exports, getEngine, join, split, url;

url = require("url");

getEngine = function(name) {
  var engine;
  try {
    return engine = require("./engines/" + name);
  } catch (error) {
    throw "Unsupported engine: " + name;
  }
};

split = function(hostString, engineName) {
  if (engineName == null) {
    engineName = "connect-redis";
  }
  return getEngine(engineName).split(url.parse(hostString));
};

join = function(hostObj, engineName) {
  if (engineName == null) {
    engineName = "connect-redis";
  }
  return url.format(getEngine(engineName).join(hostObj));
};

module.exports = exports = split;

exports.split = split;

exports.join = join;
