// Generated by CoffeeScript 1.3.1
var exports, redJoin, redSplit, redisMap, url;

url = require("url");

redisMap = {};

redSplit = function(hoststr, mapping) {
  var parsed;
  if (mapping == null) {
    mapping = redisMap;
  }
  parsed = url.parse(hoststr);
  if ((parsed.auth != null) && parsed.auth.indexOf(":") >= 0) {
    parsed.authpair = parsed.auth;
    parsed.auth = parsed.authpair.split(":").pop();
  }
  return parsed;
};

redJoin = function(hostobj) {
  if (hostobj.authpair != null) {
    hostobj.auth = hostobj.authpair;
    delete hostobj.authpair;
  }
  return url.format(hostobj);
};

module.exports = exports = redSplit;

exports.split = redSplit;

exports.join = redJoin;
