// Generated by CoffeeScript 1.3.1

exports.split = function(hostObj) {
  hostObj.pass = hostObj.auth.split(":").pop();
  hostObj.hostBackup = hostObj.host
  hostObj.host = hostObj.hostname
  return hostObj;
};

exports.join = function(hostObj) {
  delete hostObj.pass;
  hostObj.host = hostObj.hostBackup
  return hostObj;
};
