// Generated by CoffeeScript 1.3.1

exports.split = function(hostObj) {
  hostObj.pass = parsed.authpair.split(":").pop();
  return hostObj;
};

exports.join = function(hostObj) {
  delete hostObj.pass;
  return hostObj;
};
