// Generated by CoffeeScript 1.3.1

exports.split = function(hostObj) {
  hostObj.authpair = hostObj.auth;
  hostObj.auth = parsed.authpair.split(":").pop();
  return hostObj;
};

exports.join = function(hostObj) {
  hostObj.auth = hostObj.authpair;
  delete hostObj.authpair;
  return hostObj;
};
